import type { AppUser, Order } from '@/types';

export type { Order, OrderCategory, OrderStatus } from '@/types';
export type { AppUser, SubscriptionStatus } from '@/types';

export const subscriptionStatuses = [
  '期限切れ',
  '未契約',
  '契約中',
  '解約済み',
] as const;

export const users: AppUser[] = [
  {
    id: 'U-0001',
    username: 'ngocph_test',
    email: 'ngocph3@1bitlab.iongocph3@1bitlab.iongocph3@1bitlab.io',
    affiliation: '個人申込',
    trainingDays: 1,
    visionCheckDays: 1,
    checkDays: 0,
    registeredAt: '2026/09/23',
    expiresAt: '2026/09/23',
    subscriptionStatus: '期限切れ',
  },
  {
    id: 'U-0002',
    username: 'ddgg',
    email: 'a@x.com',
    affiliation: '個人申込',
    trainingDays: 0,
    visionCheckDays: 0,
    checkDays: 0,
    registeredAt: '2026/09/23',
    expiresAt: null,
    subscriptionStatus: '未契約',
  },
  {
    id: 'U-0003',
    username: 'ngocph_test3',
    email: 'ngocph@1bitlab.io',
    affiliation: 'スクロールのテスト01',
    trainingDays: 2,
    visionCheckDays: 1,
    checkDays: 0,
    registeredAt: '2026/09/22',
    expiresAt: '2026/09/30',
    subscriptionStatus: '解約済み',
  },
  {
    id: 'U-0004',
    username: 'ngocph_test4',
    email: 'ngocph2@1bitlab.io',
    affiliation: '個人申込',
    trainingDays: 0,
    visionCheckDays: 0,
    checkDays: 0,
    registeredAt: '2026/09/22',
    expiresAt: '2026/09/23',
    subscriptionStatus: '期限切れ',
  },
  {
    id: 'U-0005',
    username: 'mk',
    email: 'mkk@gmail.com',
    affiliation: 'Techplan',
    trainingDays: 0,
    visionCheckDays: 0,
    checkDays: 0,
    registeredAt: '2026/09/18',
    expiresAt: '2026/10/01',
    subscriptionStatus: '解約済み',
  },
  {
    id: 'U-0006',
    username: 'sho',
    email: 'sho56452@gmail.com',
    affiliation: 'テスト株式会社',
    trainingDays: 0,
    visionCheckDays: 0,
    checkDays: 0,
    registeredAt: '2026/09/08',
    expiresAt: '2026/09/23',
    subscriptionStatus: '解約済み',
  },
  {
    id: 'U-0007',
    username: 'abc',
    email: 'test@gmail.com',
    affiliation: 'テスト株式会社',
    trainingDays: 0,
    visionCheckDays: 0,
    checkDays: 0,
    registeredAt: '2026/09/08',
    expiresAt: '2026/09/23',
    subscriptionStatus: '解約済み',
  },
  {
    id: 'U-0008',
    username: 'abc123',
    email: 'te@gmail.cok',
    affiliation: 'Techplan',
    trainingDays: 0,
    visionCheckDays: 0,
    checkDays: 0,
    registeredAt: '2026/09/08',
    expiresAt: '2026/09/30',
    subscriptionStatus: '解約済み',
  },
  {
    id: 'U-0009',
    username: 'kljsgfdlsjk',
    email: 'axxx@gmail.com',
    affiliation: 'テスト株式会社',
    trainingDays: 0,
    visionCheckDays: 0,
    checkDays: 0,
    registeredAt: '2026/09/08',
    expiresAt: '2026/09/23',
    subscriptionStatus: '解約済み',
  },
  {
    id: 'U-0010',
    username: 'adjsldksk',
    email: 'axx@gmail.com',
    affiliation: 'テスト株式会社',
    trainingDays: 0,
    visionCheckDays: 0,
    checkDays: 0,
    registeredAt: '2026/09/08',
    expiresAt: '2026/09/23',
    subscriptionStatus: '解約済み',
  },
];

export const orderStatuses = ['Paid', 'Pending', 'Failed', 'Refunded'] as const;

export const orderCategories = ['Membership', 'Workshop', 'Retreat', 'Course'] as const;

export const orders: Order[] = [
  {
    id: 'SH-1048',
    customer: 'Sofia Martinez',
    email: 'sofia.martinez@example.com',
    initials: 'SM',
    avatarClass: 'bg-violet-100 text-violet-700',
    product: 'Mindful Foundations',
    category: 'Membership',
    date: 'Jun 24, 2026',
    amount: 129,
    status: 'Paid',
  },
  {
    id: 'SH-1047',
    customer: 'Ethan Wright',
    email: 'ethan.wright@example.com',
    initials: 'EW',
    avatarClass: 'bg-sky-100 text-sky-700',
    product: 'Breathwork Workshop',
    category: 'Workshop',
    date: 'Jun 23, 2026',
    amount: 89,
    status: 'Pending',
  },
  {
    id: 'SH-1046',
    customer: 'Ava Thompson',
    email: 'ava.thompson@example.com',
    initials: 'AT',
    avatarClass: 'bg-amber-100 text-amber-700',
    product: 'Monthly Membership',
    category: 'Membership',
    date: 'Jun 22, 2026',
    amount: 49,
    status: 'Paid',
  },
  {
    id: 'SH-1045',
    customer: 'Noah Kim',
    email: 'noah.kim@example.com',
    initials: 'NK',
    avatarClass: 'bg-emerald-100 text-emerald-700',
    product: 'Deep Rest Retreat',
    category: 'Retreat',
    date: 'Jun 21, 2026',
    amount: 249,
    status: 'Failed',
  },
  {
    id: 'SH-1044',
    customer: 'Olivia Patel',
    email: 'olivia.patel@example.com',
    initials: 'OP',
    avatarClass: 'bg-rose-100 text-rose-700',
    product: 'Mindful Foundations',
    category: 'Membership',
    date: 'Jun 20, 2026',
    amount: 129,
    status: 'Paid',
  },
  {
    id: 'SH-1043',
    customer: 'Liam Brown',
    email: 'liam.brown@example.com',
    initials: 'LB',
    avatarClass: 'bg-indigo-100 text-indigo-700',
    product: 'Meditation Course',
    category: 'Course',
    date: 'Jun 19, 2026',
    amount: 79,
    status: 'Refunded',
  },
  {
    id: 'SH-1042',
    customer: 'Emma Wilson',
    email: 'emma.wilson@example.com',
    initials: 'EW',
    avatarClass: 'bg-cyan-100 text-cyan-700',
    product: 'Monthly Membership',
    category: 'Membership',
    date: 'Jun 18, 2026',
    amount: 49,
    status: 'Pending',
  },
  {
    id: 'SH-1041',
    customer: 'James Garcia',
    email: 'james.garcia@example.com',
    initials: 'JG',
    avatarClass: 'bg-orange-100 text-orange-700',
    product: 'Breathwork Workshop',
    category: 'Workshop',
    date: 'Jun 17, 2026',
    amount: 89,
    status: 'Paid',
  },
  {
    id: 'SH-1040',
    customer: 'Mia Anderson',
    email: 'mia.anderson@example.com',
    initials: 'MA',
    avatarClass: 'bg-fuchsia-100 text-fuchsia-700',
    product: 'Deep Rest Retreat',
    category: 'Retreat',
    date: 'Jun 16, 2026',
    amount: 249,
    status: 'Paid',
  },
  {
    id: 'SH-1039',
    customer: 'Lucas Moore',
    email: 'lucas.moore@example.com',
    initials: 'LM',
    avatarClass: 'bg-lime-100 text-lime-700',
    product: 'Meditation Course',
    category: 'Course',
    date: 'Jun 15, 2026',
    amount: 79,
    status: 'Paid',
  },
];
